push_to: Revert to using github token.
SSH push is failing with;
```
Agent pid 1940
Identity added: (stdin) (tansell@tansell-glapstation)
Pushing to git+ssh://github.com/The-OpenROAD-Project-staging/OpenROAD.git
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
Connection to github.com closed by remote host.
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Error: Process completed with exit code 128.
```

Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

diff --git a/push_to/action.yml b/push_to/action.yml
--- a/push_to/action.yml
+++ b/push_to/action.yml
@@ -13,8 +13,8 @@ inputs:
   force:
     description: Should the push be forced?
     default: false
-  deployKey:
-    description: SSH private "deploy key" which has write access to staging repository.
+  deployToken:
+    description: GitHub Token that has write access to staging repository.
     required: true
 
 runs:
@@ -26,25 +26,10 @@ runs:
     shell: bash
     run: |
 
-      if [[ -z "${{ inputs.owner }}"     ]]; then echo "Missing owner value!"; exit 1; fi
-      if [[ -z "${{ inputs.repo }}"      ]]; then echo "Missing repo value!"; exit 1; fi
-      if [[ -z "${{ inputs.branch }}"    ]]; then echo "Missing branch value!"; exit 1; fi
-      if [[ -z "${{ inputs.deployKey }}" ]]; then echo "Missing deployKey value!"; exit 1; fi
-
-      # Configure ssh to ignore host key checking.
-      rm -rf ~/.ssh
-      mkdir -p ~/.ssh
-      chmod 700 ~/.ssh
-
-      cat > ~/.ssh/config << EOF
-      Host *
-        StrictHostKeyChecking no
-        UserKnownHostsFile /dev/null
-      EOF
-
-      # Start ssh agent and add deploy key.
-      eval $(ssh-agent -s)
-      ssh-add - <<< "${{ inputs.deployKey }}"
+      if [[ -z "${{ inputs.owner }}"       ]]; then echo "Missing owner value!";       exit 1; fi
+      if [[ -z "${{ inputs.repo }}"        ]]; then echo "Missing repo value!";        exit 1; fi
+      if [[ -z "${{ inputs.branch }}"      ]]; then echo "Missing branch value!";      exit 1; fi
+      if [[ -z "${{ inputs.deployToken }}" ]]; then echo "Missing deployToken value!"; exit 1; fi
 
       # Figure out if we should do a force push
       export GIT_ARGS=''
@@ -52,9 +37,6 @@ runs:
         export GIT_ARGS=--force
       fi
 
-      export GIT_TRACE=1
-      export GIT_CURL_VERBOSE=1
-
       # Add local repository and push to it.
-      git remote add origin git+ssh://git@github.com/${{ inputs.owner }}/${{ inputs.repo }}.git
+      git remote add origin https://token:${{ inputs.deployToken }}@github.com/${{ inputs.owner }}/${{ inputs.repo }}.git
       git push $GIT_ARGS origin --verbose ${{ inputs.branch }}
